export interface DiagnosticNode {
  id: string;
  title: string;
  description: string;
  type: 'question' | 'solution';
  options?: {
    label: string;
    nextNodeId: string;
  }[];
  steps?: string[];
  cautions?: string[];
}

export const diagnosticTree: Record<string, DiagnosticNode> = {
  root: {
    id: 'root',
    title: 'What ticket emergency are you facing?',
    description: 'Select your situation below to find the crowdsourced community fix instantly.',
    type: 'question',
    options: [
      { label: 'I bought tickets on StubHub/Viagogo, but they are not showing up in my FIFA account', nextNodeId: 'proxy_trap_check' },
      { label: 'I am trying to transfer a ticket to a friend, but it is stuck on "Pending"', nextNodeId: 'pending_transfer_check' },
      { label: 'My ticket transfer was completed, but my guest sees an empty wallet app', nextNodeId: 'guest_wallet_empty' }
    ]
  },

  // PATH 1: The Proxy Email Trap Branch
  proxy_trap_check: {
    id: 'proxy_trap_check',
    title: 'Did you check the confirmation email from your marketplace?',
    description: 'Look carefully at the order confirmation or delivery email sent by StubHub or Viagogo.',
    type: 'question',
    options: [
      { label: 'Yes, it mentions a weird transfer email or a "proxy" address', nextNodeId: 'proxy_trap_detected' },
      { label: 'No, it says it was sent directly to my personal email address', nextNodeId: 'direct_email_error' }
    ]
  },
  proxy_trap_detected: {
    id: 'proxy_trap_detected',
    title: '🚨 Resolution: You are caught in the Proxy Email Trap',
    description: 'Marketplaces mask buyer identities by generating a temporary proxy address (e.g., buyer.12345@stubhubproxy.com). FIFA sent the ticket invitation link to that proxy email, NOT your personal account.',
    type: 'solution',
    steps: [
      'Open your ticket marketplace dashboard (StubHub/Viagogo) and find your order details page.',
      'Locate the "Transfer/Proxy Email Address" generated specifically for this purchase.',
      'Log OUT of your personal account on the official FWC2026 Mobile Tickets App.',
      'Create a brand NEW FIFA Ticketing Account using that exact proxy email address.',
      'Verify the new account via the confirmation link (which StubHub will forward to your personal inbox within 5-10 minutes).',
      'Once logged into the FIFA app with the proxy email, your ticket QR codes will instantly populate.'
    ],
    cautions: [
      'Do not attempt to change the proxy email inside the FIFA ticketing app before the tickets render—this can break the active cryptographically-signed token distribution payload.',
      'Keep this temporary proxy login active until you are physically inside the stadium gates.'
    ]
  },
  direct_email_error: {
    id: 'direct_email_error',
    title: '🚨 Resolution: FIFA Email Sync Lag',
    description: 'If the seller transferred directly to your email address but your wallet remains completely blank, the app is experiencing local state cache desynchronization.',
    type: 'solution',
    steps: [
      'Force close the FWC2026 Mobile Tickets App on your smartphone.',
      'Go to your device App Settings -> Storage -> Clear Cache (Do not clear data yet).',
      'Check your personal inbox (and spam folder) for an automated invitation email directly from FIFA Ticketing.',
      'Click the unique confirmation link inside that official FIFA email directly from your mobile device to force the deep-link execution handler to bind the ticket UUID to your local wallet.'
    ],
    cautions: [
      'If you never received the email from FIFA, the seller may have typed a character wrong. Contact marketplace support immediately to request a seller verification proof.'
    ]
  },

  // PATH 2: Stuck Pending Transfer Branch
  pending_transfer_check: {
    id: 'pending_transfer_check',
    title: 'Is the ticket stuck on "Pending" on your seller dashboard?',
    description: 'When you look at your wallet or the marketplace portal, does the transfer state indicate it is awaiting action?',
    type: 'question',
    options: [
      { label: 'Yes, it has been stuck on "Pending" for hours/days', nextNodeId: 'stuck_pending_resolution' },
      { label: 'No, it says "Completed" on my side but the recipient has nothing', nextNodeId: 'guest_wallet_empty' }
    ]
  },
  stuck_pending_resolution: {
    id: 'stuck_pending_resolution',
    title: '🚨 Resolution: Force the Direct Invite URL Link',
    description: 'The automated transactional email system between ticketing databases is failing under heavy match-day loads.',
    type: 'solution',
    steps: [
      'Open your FWC2026 Mobile Tickets App and tap on the pending ticket asset.',
      'Tap on "Manage Transfer" or "Share Invite Link".',
      'Copy the direct URL link generated by the app straight to your clipboard.',
      'Manually send this exact string to your buyer/friend via WhatsApp, SMS, or Reddit DM.',
      'Instruct the recipient to open that URL directly on their mobile device where their FIFA app is installed to bypass the broken email distribution layer entirely.'
    ],
    cautions: [
      'Never post this unique registration link publicly on social media or forums; anyone who clicks it can claim ownership of that specific ticket ticket payload instantly.'
    ]
  },

  // PATH 3: Completed but Empty Guest Wallet
  guest_wallet_empty: {
    id: 'guest_wallet_empty',
    title: '🚨 Resolution: Dynamic Ticket Token Re-Sync',
    description: 'The transfer is completed on the ledger, but the local client wallet instance has not refreshed its layout state.',
    type: 'solution',
    steps: [
      'Have the recipient open the FWC2026 Mobile Tickets App.',
      'Pull down firmly on the main screen wallet interface to manually trigger a database sync event handler.',
      'If the tickets still do not fetch, log out of the account completely, clear the app device data cache, and log back in.',
      'Ensure the time settings on the smartphone are set to "Automatic Time Sync (NTP)". If the local system clock mismatches the FIFA server time by even 60 seconds, the rotating security QR tokens will fail to render.'
    ],
    cautions: [
      'Ensure the recipient is using the latest official update version from the iOS App Store or Google Play Store. Outdated builds completely block the new 2026 secure rolling ticket formats.'
    ]
  }
};